spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
        - id: payment-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
server:
  port: 8180
